### ISSUE TITLE
Upgrade com.ortto:androidsdk to 1.5.1

### ISSUE THREAD

**Issue by rlemasquerier** [autopilot3/ortto-flutter-sdk#1]
Hello @scrummitch @Draal 👋

Thank you for your work providing this Flutter SDK!

I've noticed you fixed some deeplink issues in [ortto-push-android-sdk](https://github.com/autopilot3/ortto-push-android-sdk) release `1.5.1`

As we are integrating the flutter SDK into our app, I'm experiencing issues regarding linking to the app (app crash when pressing the notification on android). I think that's because we are still in `1.5.0` behind the flutter SDK.

Would that make sense to upgrade the android sdk dependency from `1.5.0` to `1.5.1` in the flutter sdk and publish a new version? Seems like it would solve the issue on my side, it'd be greatly appreciated.

https://github.com/autopilot3/ortto-flutter-sdk/blob/c1940392fa46a8b49fb2e401e5fc4152b0fe957a/ortto_flutter_sdk_android/android/build.gradle#L50

Many thanks

**Comment by scrummitch** [comment]
Hi @rlemasquerier you're absolutely spot on here. The latest version of the flutter SDK includes updates to our Android SDK `(v1.5.1)` . This latest update fixes an issue where deep links without a in-app notification were sometimes causing a crash. 

Flutter SDK 0.2.3 is here https://pub.dev/packages/ortto_flutter_sdk/changelog#023

**Comment by rlemasquerier** [comment]
@scrummitch Great, thank you 👍 !
